# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build-and-test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.9

    - name: Install bazel
      run: ./hack/install-bazel.sh && ln -snf ~/bin/bazel /usr/local/bin/bazel

    - name: Go build
      run: go build -v ./...
    
    - name: Bazel build all
      run: bazel build //...

    - name: Bazel test all
      run: bazel test //...